### ISSUE TITLE
Add jenkins webhook

### ISSUE THREAD

**Issue by polytan02** [YunoHost-Apps/framagames_ynh#2]
@maniackcrudelis Please could you add the jenkins webhoook to this app ?

**Comment by maniackcrudelis** [comment]
Il me semble que tu me l'as déjà demandé et que je t'ai déjà répondu que le hook était déjà en place.

Et la liste des apps n'étant pas actualisée, ton apps ne sera probablement pas ajoutée cette nuit.
Tu penses que tu vas me le redemander à chaque ajout d'une app ?

**Comment by polytan02** [comment]
Je n'ai pas vu ta réponse comme quoi c'était fait, et je n'ai aucun moyen de la savoir via github ou jenkins.
